(() => {
  const protocolVersion = 9, scanToleranceDegrees = 10, sonarRadiusMeters = 10000, reconnectDelayMs = 1500;
  const spectrum = document.querySelector('#spectrum-canvas'), spectrumCtx = spectrum.getContext('2d');
  const bearing = document.querySelector('#bearing-canvas'), bearingCtx = bearing.getContext('2d');
  const sonar = document.querySelector('#sonar-canvas'), sonarCtx = sonar.getContext('2d');
  const library = [
    { code: 'CETUS', type: 'TRANSPORTER', color: '#d6b66a', peaks: { reactor: 432, shields: 514, propulsion: 656, weapons: 730 } },
    { code: 'ARGUS', type: 'CORVETTE', color: '#86d5b0', peaks: { reactor: 486, shields: 619, propulsion: 684, weapons: 548 } },
    { code: 'ATLAS', type: 'FRIGATE', color: '#a89bdb', peaks: { reactor: 454, shields: 572, propulsion: 702, weapons: 644 } }
  ];
  const labels = { reactor: 'REACTOR', shields: 'SHIELDS', propulsion: 'DRIVE', weapons: 'WEAPONS' };
  let socket, contacts = [], selectedLibrary = 0, scanBearing = 0, activeSonar = false, trackingEnabled = false, sweep = 0;
  const identified = new Set(); let displayedId = null;
  const byId = id => contacts.find(contact => contact.enemyId === id);
  const normalize = value => ((value + 180) % 360 + 360) % 360 - 180;
  const currentContact = () => contacts.slice().sort((a, b) => Math.abs(normalize(a.bearingDegrees - scanBearing)) - Math.abs(normalize(b.bearingDegrees - scanBearing)))[0] || null;
  const alignment = contact => contact ? Math.max(.04, Math.exp(-Math.pow(normalize(scanBearing - contact.bearingDegrees), 2) / (2 * 20 * 20))) : 0;
  const activeShip = () => library[selectedLibrary];
  function resize(canvas, ctx) { const box = canvas.getBoundingClientRect(), ratio = devicePixelRatio || 1; canvas.width = Math.max(1, Math.round(box.width * ratio)); canvas.height = Math.max(1, Math.round(box.height * ratio)); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); return box; }
  function updateLibrary() { const ship = activeShip(); document.querySelector('#ship-code').textContent = ship.code; document.querySelector('#ship-type').textContent = ship.type; document.querySelector('#ship-position').textContent = `${String(selectedLibrary + 1).padStart(2, '0')} / 03`; document.querySelector('#envelope-swatch').style.background = ship.color; drawAll(); }
  function setConnection(online) { const node = document.querySelector('#connection'); node.textContent = online ? 'SENSORIUM ONLINE' : 'SENSORIUM OFFLINE'; node.style.color = online ? '#79c9a5' : '#e88b86'; }
  function updateTrackingStatus() { const node = document.querySelector('#tracking-status'), indicator = document.querySelector('#tracking-indicator'); node.textContent = trackingEnabled ? 'TRACK ACTIVE' : 'TRACK MANUAL'; node.style.color = trackingEnabled ? '#8cdbb8' : '#9aa9a8'; indicator.className = `state-label ${trackingEnabled ? 'active' : 'inactive'}`; }
  function envelope(wavelength, ship) { const peak = center => Math.exp(-Math.pow(wavelength - center, 2) / (2 * 32 * 32)); return Math.min(45, 5 + Object.values(ship.peaks).reduce((sum, center) => sum + peak(center) * 10, 0)); }
  function signal(wavelength, contact) { if (!contact) return 0; const ship = library.find(item => item.code === contact.signatureCode); const activity = { reactor: contact.reactorOutputFraction, shields: contact.shieldFraction, propulsion: contact.propulsionOutputFraction, weapons: contact.weaponsOutputFraction }; const noise = 2 + Math.sin(wavelength / 17 + contact.enemyId) * 1.2 + Math.sin(wavelength / 8 + contact.enemyId * 2) * .6; const dynamic = Object.entries(ship.peaks).reduce((sum, [key, center]) => sum + Math.exp(-Math.pow(wavelength - center, 2) / (2 * 4.5 * 4.5)) * activity[key] * 62, 0); return Math.min(100, Math.max(0, (envelope(wavelength, ship) + noise + dynamic) * alignment(contact))); }
  function drawSpectrum() {
    const box = resize(spectrum, spectrumCtx), width = box.width, height = box.height, graph = { left: 50, right: 18, top: 32, bottom: 35 }, gw = width - graph.left - graph.right, gh = height - graph.top - graph.bottom, contact = currentContact(), ship = activeShip();
    spectrumCtx.fillStyle = '#12191a'; spectrumCtx.fillRect(0, 0, width, height); spectrumCtx.strokeStyle = '#2e3b3c'; spectrumCtx.lineWidth = 1; spectrumCtx.font = '10px ui-monospace, monospace'; spectrumCtx.fillStyle = '#879794'; spectrumCtx.textAlign = 'right';
    [0, 25, 50, 75, 100].forEach(value => { const y = graph.top + gh - value / 100 * gh; spectrumCtx.beginPath(); spectrumCtx.moveTo(graph.left, y); spectrumCtx.lineTo(width - graph.right, y); spectrumCtx.stroke(); spectrumCtx.fillText(value, graph.left - 7, y + 3); });
    spectrumCtx.textAlign = 'center'; [400, 500, 600, 700, 780].forEach(value => { const x = graph.left + (value - 380) / 400 * gw; spectrumCtx.beginPath(); spectrumCtx.moveTo(x, graph.top); spectrumCtx.lineTo(x, graph.top + gh); spectrumCtx.stroke(); spectrumCtx.fillText(value, x, height - 16); });
    Object.entries(ship.peaks).forEach(([key, wavelength]) => { const x = graph.left + (wavelength - 380) / 400 * gw; spectrumCtx.setLineDash([4, 4]); spectrumCtx.strokeStyle = ship.color; spectrumCtx.globalAlpha = .7; spectrumCtx.beginPath(); spectrumCtx.moveTo(x, graph.top); spectrumCtx.lineTo(x, graph.top + gh); spectrumCtx.stroke(); spectrumCtx.setLineDash([]); spectrumCtx.globalAlpha = 1; spectrumCtx.fillStyle = ship.color; spectrumCtx.font = '9px ui-monospace, monospace'; spectrumCtx.fillText(labels[key], x, graph.top + 11); });
    const bins = 80, step = gw / bins; for (let index = 0; index < bins; index++) { const wavelength = 380 + index * 5 + 2.5, intensity = signal(wavelength, contact), bar = intensity / 100 * gh; spectrumCtx.fillStyle = intensity >= 58 ? '#a6ddb0' : '#5bbd9b'; spectrumCtx.fillRect(graph.left + index * step + 1, graph.top + gh - bar, Math.max(1, step - 2), bar); }
    spectrumCtx.strokeStyle = ship.color; spectrumCtx.lineWidth = 2; spectrumCtx.beginPath(); for (let point = 0; point <= 120; point++) { const wavelength = 380 + point / 120 * 400, x = graph.left + point / 120 * gw, y = graph.top + gh - envelope(wavelength, ship) / 100 * gh; point ? spectrumCtx.lineTo(x, y) : spectrumCtx.moveTo(x, y); } spectrumCtx.stroke();
    const state = document.querySelector('#spectrum-state'), error = contact ? Math.abs(normalize(scanBearing - contact.bearingDegrees)) : Infinity; state.textContent = contact ? (error <= scanToleranceDegrees ? `SIGNAL ${Math.round(alignment(contact) * 100)} %` : 'WEAK SIGNAL') : 'NO SIGNAL'; state.className = `state-label ${error <= scanToleranceDegrees ? 'active' : 'muted'}`;
  }
  function drawBearing() {
    const box = resize(bearing, bearingCtx), size = Math.min(box.width, box.height), cx = box.width / 2, cy = box.height / 2, radius = size * .36, radians = (scanBearing - 90) * Math.PI / 180;
    bearingCtx.fillStyle = '#12191a'; bearingCtx.fillRect(0, 0, box.width, box.height); bearingCtx.strokeStyle = '#304041'; bearingCtx.lineWidth = 1; [1, .66, .33].forEach(scale => { bearingCtx.beginPath(); bearingCtx.arc(cx, cy, radius * scale, 0, Math.PI * 2); bearingCtx.stroke(); });
    bearingCtx.strokeStyle = '#8cdbb8'; bearingCtx.lineWidth = Math.max(2, size * .012); bearingCtx.beginPath(); bearingCtx.moveTo(cx, cy); bearingCtx.lineTo(cx + Math.cos(radians) * radius, cy + Math.sin(radians) * radius); bearingCtx.stroke(); bearingCtx.fillStyle = '#dce8e1'; bearingCtx.beginPath(); bearingCtx.moveTo(cx, cy - size * .075); bearingCtx.lineTo(cx + size * .047, cy + size * .06); bearingCtx.lineTo(cx, cy + size * .032); bearingCtx.lineTo(cx - size * .047, cy + size * .06); bearingCtx.fill(); bearingCtx.fillStyle = '#8cdbb8'; bearingCtx.font = `${Math.max(9, size * .05)}px ui-monospace, monospace`; bearingCtx.textAlign = 'right'; bearingCtx.fillText(`${scanBearing >= 0 ? '+' : ''}${Math.round(scanBearing)} DEG`, box.width - 10, box.height - 10);
  }
  function drawSonar() {
    const box = resize(sonar, sonarCtx), size = Math.min(box.width, box.height), cx = box.width / 2, cy = box.height / 2, radius = size * .38, range = sonarRadiusMeters; sonarCtx.fillStyle = '#101a17'; sonarCtx.fillRect(0, 0, box.width, box.height); sonarCtx.strokeStyle = '#295044'; sonarCtx.lineWidth = 1; [1, .75, .5, .25].forEach(scale => { sonarCtx.beginPath(); sonarCtx.arc(cx, cy, radius * scale, 0, Math.PI * 2); sonarCtx.stroke(); });
    const sweepAngle = (sweep - 90) * Math.PI / 180; sonarCtx.strokeStyle = '#7ed6a7'; sonarCtx.lineWidth = Math.max(1, size * .008); sonarCtx.beginPath(); sonarCtx.moveTo(cx, cy); sonarCtx.lineTo(cx + Math.cos(sweepAngle) * radius, cy + Math.sin(sweepAngle) * radius); sonarCtx.stroke();
    contacts.filter(contact => contact.distanceMeters <= range).forEach(contact => { const angle = (contact.bearingDegrees - 90) * Math.PI / 180, distance = contact.distanceMeters / range, x = cx + Math.cos(angle) * radius * distance, y = cy + Math.sin(angle) * radius * distance, isIdentified = identified.has(contact.enemyId); sonarCtx.fillStyle = '#ef7772'; sonarCtx.beginPath(); sonarCtx.arc(x, y, Math.max(3, size * .023), 0, Math.PI * 2); sonarCtx.fill(); if (isIdentified) { sonarCtx.strokeStyle = '#e5c36c'; sonarCtx.lineWidth = 2; sonarCtx.beginPath(); sonarCtx.arc(x, y, Math.max(8, size * .045), 0, Math.PI * 2); sonarCtx.stroke(); } if (displayedId === contact.enemyId) { sonarCtx.strokeStyle = '#91e0c2'; sonarCtx.strokeRect(x - 12, y - 12, 24, 24); } }); sonarCtx.fillStyle = '#8da99b'; sonarCtx.font = `${Math.max(7, size * .04)}px ui-monospace, monospace`; sonarCtx.textAlign = 'left'; sonarCtx.fillText('ACTIVE SONAR  /  10 KM', 10, 15);
  }
  function showContact(contact) { if (!contact) return; displayedId = contact.enemyId; const set = (id, text) => document.querySelector(id).textContent = text; set('#contact-name', contact.name); set('#contact-class', `${contact.signatureCode} ${contact.shipClass}`); set('#contact-reactor', `${Math.round(contact.reactorOutputFraction * 100)} %`); set('#contact-shields', `${Math.round(contact.shieldFraction * 100)} %`); set('#contact-propulsion', `${Math.round(contact.propulsionOutputFraction * 100)} %`); set('#contact-weapons', `${Math.round(contact.weaponsOutputFraction * 100)} %`); set('#contact-distance', `${(contact.distanceMeters / 1000).toFixed(2)} KM`); set('#contact-hull', `${contact.hull} / ${contact.maximumHull}`); document.querySelector('#contact-empty').hidden = true; document.querySelector('#contact-data').classList.remove('is-hidden'); const status = document.querySelector('#contact-status'); status.textContent = 'CONFIRMED'; status.className = 'state-label confirmed'; }
  function sendIdentification(enemyId) { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: 'identify_contact', enemyId })); }
  function confirm() { const contact = currentContact(), status = document.querySelector('#contact-status'); if (!contact || Math.abs(normalize(scanBearing - contact.bearingDegrees)) > scanToleranceDegrees || activeShip().code !== contact.signatureCode) { status.textContent = 'MISMATCH'; status.className = 'state-label mismatch'; return; } identified.add(contact.enemyId); sendIdentification(contact.enemyId); showContact(contact); drawAll(); }
  function cycleIdentified() { const list = contacts.filter(contact => identified.has(contact.enemyId)); if (!list.length) return; const next = list[(Math.max(0, list.findIndex(contact => contact.enemyId === displayedId)) + 1) % list.length]; showContact(next); if (trackingEnabled) scanBearing = next.bearingDegrees; drawAll(); }
  function sendActiveSonarPing() { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: 'active_sonar' })); }
  function toggleMode() { activeSonar = !activeSonar; sendActiveSonarPing(); document.querySelector('#bearing-frame').hidden = activeSonar; document.querySelector('#sonar-frame').hidden = !activeSonar; document.querySelector('#array-heading').textContent = activeSonar ? 'Active Sonar' : 'Spectrometer Bearing'; const mode = document.querySelector('#array-mode'); mode.textContent = activeSonar ? 'ACTIVE' : 'PASSIVE'; mode.className = `state-label ${activeSonar ? 'active' : 'muted'}`; drawAll(); }
  function toggleTracking() { if (displayedId === null || !identified.has(displayedId) || !byId(displayedId)) return; trackingEnabled = !trackingEnabled; if (trackingEnabled) scanBearing = byId(displayedId).bearingDegrees; updateTrackingStatus(); drawAll(); }
  function drawAll() { drawSpectrum(); if (activeSonar) drawSonar(); else drawBearing(); }
  function update(next) { contacts = Array.isArray(next.contacts) ? next.contacts : []; [...identified].forEach(id => { if (!byId(id)) identified.delete(id); }); if (displayedId !== null && !byId(displayedId)) { displayedId = null; trackingEnabled = false; } if (displayedId !== null && identified.has(displayedId)) { const displayed = byId(displayedId); showContact(displayed); if (trackingEnabled) scanBearing = displayed.bearingDegrees; } updateTrackingStatus(); document.querySelector('#scan-id').textContent = `SCAN ${String(next.simulationTick || 0).padStart(4, '0')}`; drawAll(); }
  function connect() { const scheme = location.protocol === 'https:' ? 'wss' : 'ws'; socket = new WebSocket(`${scheme}://${location.host}/station`); socket.onopen = () => socket.send(JSON.stringify({ type: 'hello', station: 'sensorium', protocolVersion })); socket.onmessage = event => { const message = JSON.parse(event.data); if (message.type === 'welcome') setConnection(true); if (message.type === 'sensorium_state') update(message); if (message.type === 'error') setConnection(false); }; socket.onclose = () => { setConnection(false); setTimeout(connect, reconnectDelayMs); }; socket.onerror = () => socket.close(); }
  document.querySelector('#previous-ship').onclick = () => { selectedLibrary = (selectedLibrary + 2) % 3; updateLibrary(); }; document.querySelector('#next-ship').onclick = () => { selectedLibrary = (selectedLibrary + 1) % 3; updateLibrary(); };
  document.addEventListener('keydown', event => { const key = event.key.toLowerCase(); if (key === 'p' && !event.repeat) { event.preventDefault(); toggleTracking(); } else if (key === 'o' && !event.repeat) { event.preventDefault(); toggleMode(); } else if (key === 'l' && !event.repeat) { event.preventDefault(); cycleIdentified(); } else if (key === 'arrowleft' || key === 'arrowright') { event.preventDefault(); selectedLibrary = (selectedLibrary + (key === 'arrowleft' ? 2 : 1)) % 3; updateLibrary(); } else if ((key === 'a' || key === 'd') && !activeSonar) { event.preventDefault(); trackingEnabled = false; scanBearing = normalize(scanBearing + (key === 'a' ? -2 : 2)); updateTrackingStatus(); drawAll(); } else if (event.key === 'Enter' && !event.repeat) { event.preventDefault(); confirm(); } });
  window.addEventListener('resize', drawAll); updateLibrary(); updateTrackingStatus(); setConnection(false); requestAnimationFrame(function animate(time) { sweep = time / 7 % 360; if (activeSonar) drawSonar(); requestAnimationFrame(animate); }); connect();
})();
