<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>SpaceSim.GodotClient</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SpaceSim.Core/SpaceSim.Core.csproj" />
    <ProjectReference Include="../SpaceSim.Stations/SpaceSim.Stations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Armarium/**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Voltarium/**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Sensorium/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
