const defaults={mainBoosterKilonewtons:144,reverseBoosterKilonewtons:72,sideBoosterKilonewtons:4.68,shieldRechargeSeconds:5,lanceRangeMeters:1000,lanceChargeSeconds:3};
const fields=[['mainBoosterKilonewtons','Haupttriebwerk','kN',1,.1],['reverseBoosterKilonewtons','Reverse Booster','kN',1,.1],['sideBoosterKilonewtons','Side Booster','kN',.1,.01],['shieldRechargeSeconds','Schild-Aufladezeit','s',.2,.1],['lanceRangeMeters','Lanzenreichweite','m',50,10],['lanceChargeSeconds','Lanzen-Aufladezeit','s',.1,.1]];
const el=id=>document.getElementById(id); let sessions=[];
function form(side,value=defaults){const box=document.querySelector(`[data-side="${side}"]`);box.innerHTML=`<legend>${side==='nomad'?'NOMAD':'GEGNER'}</legend>`+fields.map(([key,label,unit,min,step])=>`<div class="field"><label for="${side}-${key}">${label}</label><input id="${side}-${key}" type="number" min="${min}" step="${step}" value="${value[key]??defaults[key]}"><span class="unit">${unit}</span></div>`).join('')}
function read(side){const data={};fields.forEach(([key])=>data[key]=Number(el(`${side}-${key}`).value));return data}
function fmt(value,digits=1){return Number(value||0).toFixed(digits)}
function showForm(copy){el('overview').classList.add('hidden');el('formPanel').classList.remove('hidden');form('nomad',copy?.nomad);form('enemy',copy?.enemy);el('battleCount').value=copy?.battleCount||5;el('runState').textContent=''}
function overview(session){el('formPanel').classList.add('hidden');el('overview').classList.remove('hidden');if(session.configured===false||(!session.nomad&&!session.enemy)){el('overview').innerHTML=`<div class="dashboard"><div class="title-row"><div><span>ÄLTERER LAUF</span><h2>${session.id}</h2></div><button id="reuse">MIT STANDARDWERTEN TESTEN</button></div><p class="hint">Für diesen älteren Lauf liegt noch keine Parametermetadatei vor. Die vorhandenen Detail-Logs bleiben im Duell-Log-Viewer verfügbar.</p></div>`;el('reuse').onclick=()=>showForm();return}const wins=session.nomadWins+session.enemyWins;el('overview').innerHTML=`<div class="dashboard"><div class="title-row"><div><span>GESPEICHERTER LAUF</span><h2>${session.id}</h2></div><button id="reuse">KONFIGURATION KOPIEREN</button></div><h2>VERWENDETE PARAMETER</h2><div class="parameters">${table('NOMAD',session.nomad)}${table('GEGNER',session.enemy)}</div><h2 style="margin-top:24px">STATISTIK</h2><div class="summary"><div class="card"><span>NOMAD-SIEGE</span><b class="green">${session.nomadWins}</b></div><div class="card"><span>GEGNER-SIEGE</span><b class="orange">${session.enemyWins}</b></div><div class="card"><span>TIMEOUTS</span><b class="red">${session.timeouts}</b></div><div class="card"><span>GEFECHTE</span><b>${session.battleCount}</b></div></div><h2 style="margin-top:24px">EINZELERGEBNISSE</h2><div class="battles">${(session.battles||[]).map(b=>`<div class="battle"><span>GEFECHT ${String(b.number).padStart(2,'0')}</span><b class="${b.outcome==='nomad_sieg'?'green':b.outcome==='gegner_sieg'?'orange':'red'}">${b.outcome.replace('_',' ')}</b><small>${fmt(b.durationSeconds,1)} s · min. ${fmt(b.minimumDistanceMeters,0)} m</small></div>`).join('')}</div><p class="hint">Siege Nomad/Gegner: ${wins ? fmt(session.nomadWins/wins*100,0)+'% / '+fmt(session.enemyWins/wins*100)+'%' : 'keine Entscheidung'}</p></div>`;el('reuse').onclick=()=>showForm(session)}
function table(title,p){return `<table><thead><tr><th colspan="2">${title}</th></tr></thead><tbody>${fields.map(([key,label,unit])=>`<tr><td>${label}</td><td>${p[key]} ${unit}</td></tr>`).join('')}</tbody></table>`}
async function load(){const response=await fetch('/api/sessions');sessions=await response.json();const list=el('sessions');list.innerHTML=sessions.length?'':'<p class="muted">Noch keine Läufe.</p>';sessions.forEach(s=>{const b=document.createElement('button');b.className='session';b.innerHTML=`<b>${s.id}</b><small>${s.battleCount} Gefechte · ${s.configured?`${s.nomadWins}:${s.enemyWins} · ${s.timeouts} TO`:'älterer Lauf'}</small>`;b.onclick=async()=>{document.querySelectorAll('.session').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(s.configured){const r=await fetch('/api/session/'+encodeURIComponent(s.id));overview(await r.json())}else overview(s)};list.append(b)})}
el('newBattle').onclick=()=>showForm();el('cancel').onclick=()=>{el('formPanel').classList.add('hidden');el('overview').classList.remove('hidden')};el('run').onclick=async()=>{const button=el('run');button.disabled=true;el('runState').textContent='Simulation läuft – alle Ticks werden ohne Echtzeitwartezeit berechnet …';try{const response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({battleCount:Number(el('battleCount').value),nomad:read('nomad'),enemy:read('enemy')})});if(!response.ok)throw new Error((await response.text())||'Serverfehler');const result=await response.json();await load();overview(result)}catch(error){el('runState').textContent='Fehler: '+error.message}finally{button.disabled=false}};load().catch(error=>el('sessions').innerHTML=`<p class="muted">Serverfehler: ${error.message}</p>`);
